// Interface for when creating a new product, without the 'id'
interface CreateProductDTO {
    created_at: string; // Date string since it's timestamp with time zone
    name: string;
    slug: string;
    price: number;
    discount_price: number;
    discount_percentage: number;
    images: string[];
    description: string;
    brand: string;
    category: string;
    gender: Gender
    user_id: string; // Provided by the user
}

// Interface for a product retrieved from the database, with the 'id'
interface Product extends CreateProductDTO {
    id: string; // Automatically generated by the database
}

interface UserFavoriteDto {
    user_id: string;
    product_id: string;
}
interface UserFavorite extends UserFavoriteDto {
    created_at: string
}

type Gender = 'male' | 'female' | 'children';