/* eslint-disable unused-imports/no-unused-vars */
// Interface for when creating a new product, without the 'id'
interface CreateProductDTO {
  brand: string | null;
  category: Category | null;
  category_id?: string | null;
  store_id?: string | null;
  created_at: string; // Date string since it's timestamp with time zone
  description: string | null;
  discount_percentage: number | null;
  regular_price: number | null;
  gender: Gender | null;
  images: string[] | null;
  name: string | null;
  price: number | null;
  slug: string | null;
  user_id: string | null;
  sizes: string[]; // Provided by the user
}

// Interface for a product retrieved from the database, with the 'id'
interface Product extends CreateProductDTO {
  id: number; // Automatically generated by the database
}

interface FavoriteProduct {
  product_id: number;
  products: Product;
}

interface UserFavoriteDto {
  user_id: string;
  product_id: string;
}
interface UserFavorite extends UserFavoriteDto {
  created_at: string;
}

type Gender = "Hombre" | "Mujer" | "Niños/as" | "Remates";

type Category = "Jeans" | "Camisetas" | "Blusas" | "Camisas" | "Shorts";
/* eslint-enable unused-imports/no-unused-vars */
